package basic.test;

import static org.junit.Assert.*;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLOutput;
import java.util.ArrayList;

import org.junit.Before;
import org.junit.Test;

import basic.Basic;
import efficient.Efficient;
import excelWriter.writeXLSX;



public class TestInputStringGenerator {
	Basic parsedFile;
	static ArrayList<String> listOfPaths;
	static String[] dnaA;
	static String[] dnaB;

	/**
	 * SETTING UP BEFORE TEST
	 * @throws Exception
	 */
	@Before
	public void setUp() throws Exception {

		//need to be RELATIVE PATH  for this to work on everyones machine or use full path but do not commit 
		//String filePath = "ProjectRequirements\\\\datapoints\\\\";
		//String filePath = "ProjectRequirements\\\\SampleTestCases\\\\";
		//String filePath = "ProjectRequirements//SampleTestCases//";  //path fix for MacOS
		//String filePath = "ProjectRequirements//datapoints//";
		String filePath = "ProjectRequirements//SampleTestCases//";



		// if new file then need to add testing measurements to dnaA and dnaB
		String[] listOfFiles = new String[]{
				"input1.txt",
//				"in0.txt",
//				"in1.txt",
//				"in2.txt",
//				"in3.txt"
//				"in4.txt",
//				"in5.txt",
//				"in6.txt",
//				"in7.txt",
//				"in8.txt",
//				"in9.txt",
//				"in10.txt",
//				"in11.txt",
//				"in12.txt",
//				"in13.txt",
//				"in14.txt",
//				"in15.txt",
//				"in16.txt",
//				"in17.txt",
//				"in18.txt",
//				"in19.txt",
//				"in20.txt",
//				"in21.txt"
				//generation of new points 12/6/22
//				"in22.txt"
//				"in23.txt"
//				"in24.txt"
		};
		
		// if new file then need to add testing measurements to dnaA and dnaB
//		String[] listOfFiles = new String[]{
//											"input1.txt",
//											"input2.txt",
//											"input3.txt",
//											"input4.txt",
//											"input5.txt",
//};

		listOfPaths = new ArrayList<>();
		for(String str : listOfFiles) {
			listOfPaths.add(filePath + str); 
		}
		
		
		//testing against dna A 
		dnaA = new String[]{
				//"ww",
				"ACACTGACTACTGACTGGTGACTACTGACTGG",
				"CCACCAGG",
				"CTTCTCTTCTTCTTCCCTTCCTCTTCCCTTCC",
				"GGTGTGTGTCACACACATGTGTGTCAGGTGTGTGTCACACACATGTGTGTCACACACACACACA",
				"AAGGAAGGAAAGGAAGGAGGAAGGAGGAAGAAGGAAGAAGGAAGGAAAGGAAGGAGGAAGGAGGAAGAAGGAAGGAAAGGAAGGAGGAAGGAGGAAGGAGAGAAAGGAAGGAGGAAGGAGGAAGGAGA",
				"TTTTTTTCTTTTTTCTTCCTTCTTTCTTTTTTTTCTTTTTTCTTCCTTCTTTCTTCCTTCTCCTTCTTTCTTCCTTCTTTCTTTTTTCTTCCTTCTTTCTTCCTTCTCCTTCTTTCTTCCTTCTCCTTCTCCTTCTTTCTTCCTTCTTTCTTTTTTCTTCCTTCTTTCTTCCTTCTCCTTCTTTCTTCCTTC",
				"GTGTCGTGTGTGTCGTGTGTCGTGTCACAACAGTGTCGGTGTCGTGTGTGTCGTGTGTCGTGTCACAACAGTGTCGTGTCACAACAGTCACAACAGTGTCGTGTCACAACAGTCGTGTCACAACAGTGTCGTGTCACAACAGTCACAACAGTGTCGTGTCACAACATGTCACAACAGTCACAACAGTGTCGTGTCACAACAGTCGTGTCACAACAGTGTCGTGTCACAACAGTCACAACAGTGTCGTGTCACAACA",
				"TGTGGGTGTGTGTGTGGGTGTGTGGGTGTGGTGTGGGTGTGTGTTGTGGGTGTGTGTGTGGGTGTGTGGGTGTGGTGTGGGTGTGTGTGTGGGTGTGTGGGTGTGGTGTGGGTGTGTGTGTGGGTGTGTGGGTGTGGGTGGGGGTGTGGGTGGGGTGGGGGTGTGGGTGGGTGTGGGTGTGTGTGTGGGTGTGTGGGTGTGGGTGGGGGTGTGGGTGGGGTGGGGGTGTGGGTGGGGTGGGTGTGTGGGTGTGGTGTGGGTGTGTGTGTGGGTGTGTGGGTGTGGGTGGGGGTGTGGGTGGGGTGGGGGTGTGGGTGGGTGTGGGTGTGTGTGTGGGTGTGTGGGTGTGGGTGGGGGTGTGGGTGGGGTGGGGGTGTGGGTGGG",
				"GTGTGTCGTGTGTGTCGTGTGTCTCTGTCTCTTCTGTCGTGTGTCGTGTGTGTCGTGTGTCTCTGTCTCTTCTGTCTCTGTGTCTCTGTCTCTTCTGTCTCTTCTGGTGTGTCGTGTGTGTCGTGTGTCTCTGTCTCTTCTGTCGTGTGTCGTGTGTGTCGTGTGTCTCTGTCTCTTCTGTCTCTGTGTCTCTGTCTCTTCTGTCTCTTCTGTGTCTCTGTCTCTTCTGTCTCTTGTGTGTGTCGTGTGTGTCGTGTGTCTCTGTCTCTTCTGTCGTGTGTCGTGTGTGTCGTGTGTCTCTGTCTCTTCTGTCTCTGTGTCTCTGTCTCTTCTGTCTCTTCTGGTGTGTCGTGTGTGTCGTGTGTCTCTGTCTCTTCTGTCGTGTGTCGTGTGTGTCGTGTGTCTCTGTCTCTTCTGTCTCTGTGTCTCTGTCTCTTCTGTCTCTTCTGTGTCTCTGTCTCTTCTGTCTCTTGTCTCTGTCTCTTCTGTCTCTCTCTGTCTCTTCTGTCTCT",
				"AAACCTACCTTTCCTACCTTTAAACCTACCTTTCCAAAAAACCTACCTTTCCTACCTTTAAACCTACCTTTCCAAACCTACCTTTCCTACCTTTAAACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTACCTACCTTTCCTACCAAACCTACCTTTCCTACCTTTAAACCTACCTTTCCAAAAAACCTACCTTTCCTACCTTTAAACCTACCTTTCCAAACCTACCTTTCCTACCTTTAAACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTTACCTTTACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTCCTACCTTTCCTACCTTTAAACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTTACCTTTACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTTTTTACCTTTACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTCCTACCTTTCCTACCTTTAAACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTTTACCTTTACCTACCTTTCCTACCTTTACCTACCTTTCCTACCTTT",
				"CACACACACACCCCCACACACACCCCCACACACCCCCACACACACACACACCCCCACACACACCCCCACACACCCCCACACACACCCACACACACACCCCCACACACACCCCCACACACCCCCACACACACACACACCCCCACACACACCCCCACACACCCCCACACACACCCCCCACACACACACCCCCACACACACCCCCACACACCCCCACACACACACACACCCCCACACACACCCCCACACACCCCCACACACACCCACACACACACCCCCACACACACCCCCACACACCCCCACACACACACACACACCCCCACACACACCCCCACACACCCCCACACACACACACACCCCCACACACACCCCCACACACCCCCACACACACCCACACACACACCCCCACACACACCCCCACACACCCCCACACACACACACACCCCCACACACACCCCCACACACCCCCACACACACCCCCCACACACACACCCCCACACACACCCCCACACACCCCCACACACACACACACCCCCACACACACCCCCACACACCCCCACACACACCCACACACACACCCCCACACACACCCCCACACACCCCCACACACACACACACCCCCACACACACCCCCACACACCCCCACACACACCCCCACACCCCCCCACACCCCACACCCCCCCACACCCCCACACACACCCCCACACACACCCCCACACACCCCCACACACACCCCCACACCCCCCCACACCCCACACCCCCCCACACCCC",
				"TATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTATATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTGTAGTGTTATTATAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTGTAGTGTTATTATAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTGTAGTGTTATTATAGTGTAGTGTGTTGTAGTGTTATTATAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTGTAGTGTTATTATAGTGTAGTGTGTGTAGTGTTATTATAGTGTAGTGTGTTGTAGTGTTATTATAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTGTAGTGTTATTATAGTGTAGTGTGTGTGTAGTGTTATTATAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTGTAGTGTTATTATAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTGTAGTGTTATTATAGTGTAGTGTGTTGTAGTGTTATTATAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTGTAGTGTTATTATAGTGTAGTGTGTGTAGTGTTATTATAGTGTAGTGTGTTGTAGTGTTATTATAGTGTAGTTATTATTATTATAGTGTAGTGTTATTATAGTGTAGTGTAGTGTAGTGTTATTATAGTGTAGTGTGT",
				"CATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTCATCATTGCATTGCACATCATTGCATTGCATTGCATTGCATTGCATTCATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTCATCATTGCATTGCACATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTCATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGTTGCATTGCATTGCATTGCATTGCATTGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGCATTGCATTCATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGTTGCATTGCATTGCATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTCATCATTGCATTGCACATCATTGCATTGCATTGCATTGCATTGCATTCATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTCATCATTGCATTGCACATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTCATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGTTGCATTGCATTGCATTGCATTGCATTGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGCATTGCATTCATCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGTTGCATTGCATTGCATTGCATTGCATTGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTGGTGCATTGCATTGCATTGCATTGCATTGCATTGCATTG",
				"ACACAACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACACACAACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACACAACACCACCCACCCCAACACAACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACACACAACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCCCCACCCACCAACACCACCCACCCCACCCACCCACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCCCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCCCCCACCCACCAACACCACCCACCCCACCCACCCACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACACACAACACCACCCACCCCACCCACCAACACCACCCACCCCACCCACCC",
				"AAGAGAAAAGAGAAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAAGAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAAGAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGATTAGAGATTAAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAAGAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAAGAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGATTAGAGATTAAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATTAGAGAAAAGAGAAAGAGATTAGAGATTAAGAGAAAAGAGAAAGAGATTAGAGATT",
				"GTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCGTCTGATCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCCTACCCGAGTCTGATCTACCCGAAGTCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCCTGGTGCCGGGCCAGTCTGGTGCCGGGCCGCC"
				
				};
		//testing for dna B 
		dnaB = new String[]{
				//"ww",
				"TATTATACGCTATTATACGCGACGCGGACGCG",
				"CATGCATG",
				"CCCCGACGACCCCCGACGACCGACGACGACGA",
				"AAAAAAAATTTTAAAAAAATTTTATTTTATTTTAAAAAATTTTAAAAAAATTTTATTTTATTTT",
				"GCGCCGCGCCCGCGCCCGCGCCCCCCCGCGCCCCCCCCGCGCCGCGCCCGCGCCCGCGCCCCCCCGCGCCCCCCCCGCGCCCGCGCCCCCCCGCGCCCCCCCGCGCCCGCGCCCCCCCGCGCCCCCCC",
				"AGAAGAGTTAGAAAAGAAGAGTTAGAAAGAAGAGTTAGAAGAGTTGTTGTTGAGTTGTTGTTGAAGAGTTAGAAGAGTTGTTGTTGAGTTGTAGAAGAGTTAGAAAAGAAGAGTTAGAAAGAAGAGTTAGAAGAGTTGTTGTTGAGTTGTTGTTGAAGAGTTAGAAGAGTTGTTGTTGAGTTGTTGTTTGTT",
				"AGTAAGTAGTAAGTAAAGTAAGTAGTAAGTAAGTAGTAAGTAAGTAAGTAAAGTAAAGTAGTAAGTAAGTAAGTAAAGTAGTAGTAAGTAAGTAAGTAAAGTAAAGTAGTAAAGTAAGTAGTAAGTAAAGTAAGTAGTAAGTAAGTAGTAAGTAAGTAAGTAAAGTAAAGTAGTAAGTAAGTAAGTAAAGTAGTAGTAAGTAAGTAAGTAAAGTAAAGTAGTAAGTAAGTAAGTAAAGTAGTAAGTAAGTAAAGTA",
				"GGAGAGGAGATGGAGATGATTGAGATGATTGATGATAGATGATTGAGATGATTGATGATGATTGAGATGATTGATGATAGATGATTGAGATGATTGATGATTGGAGAGGAGATGGAGATGATTGAGATGATTGATGATAGATGATTGAGATGATTGATGATGATTGAGATGATTGATGATAGATGATTGAGATGATTGATGATTGGAGATGATTGAGATGATTGATGATAGATGATTGAGATGATTGATGATGATTGAGATGATTGATGATAGATGATTGAGATGATTGATGATGGAGATGATTGAGATGATTGATGATAGATGATTGAGATGATTGATGATGATTGAGATGATTGATGATAGATGATTGAGATGATTGATGAT",
				"GTATGGTATGGTATGTATGTATGTATGGTATGGTATGTATGTATGGTATGTATTAGTATGGTATGTATTATTTAGTATGGTATGTATGTATGGTATGTATTAGTATGGTATGTATTATTTAGTATGGTATGTATTATTGTATGGTATGTATTATTGTATGTATGTATGGTATGTATTAGTATGGTATGTATTATTTAGTATGGTATGTATGTATGGTATGTATTAGTATGGTATGTATTATTTAGTATGGTATGTATTATTGTATGGTATGTATTATTGGTATGTATTAGTATGGTATGTATTATTTAGTATGGTATGTATGTATGGTATGTATTAGTATGGTATGTATTATTTAGTATGGTATGTATTATTGTATGGTATGTATTATTGTATGTATGTATGGTATGTATTAGTATGGTATGTATTATTTAGTATGGTATGTATGTATGGTATGTATTAGTATGGTATGTATTATTTAGTATGGTATGTATTATTGTATGGTATGTATTATT",
				"GGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAGGGGTTGGGGTTGGTTAGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAGGGGTTGGGGTTGGTGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAGGGGTTGGGGTTGGTTAGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAAAGTTAAAATTGGTTAAGGTTAATTGGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAAAGTTAAATAATTGGTTAAGGTTAATTGGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAAAGTTAAAATTGGTTAAGGTTAATTGGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAGGGGTTGGGGTTGGTTAATTGGTTAAGGTTAATTGGTTAAAGTTAAA",
				"TTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTTTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCCTCTCTCTCTCTCTCTCTCTTTCTTTTTCTCTCTCTCTCTCTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCCTCTCTCTCTCTCTCTCTCTTTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCCTCTCTCTCTCTCTCTCTCTTTCTTTTTCTCTCTCTCTCTCTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTTTTTCTTTTTCTCTCTTTTTCTTTTTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCCTCTCTCTCTCTCTCTCTC",
				"GCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCAACAAGCCGCCAACAACAAGCCGCCGCCGCGCCGCCAAGCCGCGCCGGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCAACAAGCCGCCAACAACAAGCCGCCGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCAACAAGCCGCCAACAACAAGCCGCCAAGCCAACAGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCAACAAGCCGCCAACAACAAGCCGCCAAGCCAACAAGCCGCCAACAACAAGCCGCCAAAGCCGCCAACAACAAGCCGCCAAAAGCCAACAGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCAACAAGCCGCCAACAACAAGCCGCCAAGCCAACAAGCCGCCAACAACAAGCCGCCAAAGCCGCCAACAACAAGCCGCCAACGCCGCCAAGCCGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCAACAAGCCGCCAACAACAAGCCGCCAAGCCAACAGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCAACAAGCCGCCAACAACAAGCCGCCAAGCCAACAAGCCGCCAACAACAAGCCGCCAAAGCCGCCAACAACAAGCCGCCAAAAGCCAACAGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCGCGCCGCCAAGCCGCGCCGCGCCGCCAAGCCGCCAACAAGCCGCCAACAACAAGCCGCCAAGCCAACAAGCCGCCAACAACAAGCCGCCAAAGCCGCCAACAACAAGCCGCCAA",
				"AAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAGTTGAGTGTTGAGTAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAGTTAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAGTTGAGTGTTGAGTAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAGTTAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAGTTGAGTGTTGAGTAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAGTTGAGTGTTGAGTAGAAGAGTGAGTTGAGTGTTGAGTGAGTGTTGAGTAGAAGAGTGAGTTGAGTGTTGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAGTTGAGTGTTGAGTAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAAAGAGAAGAGTGAAAGAGAAGAGTGAGTTGAGTGTTGAGTAAGAGAAGAGTGAGTTGAGTGTTGAGTAGAAGAGTGAGTTGAGTGTTGAGTGAGTGTTGAGTAGAAGAGTGAGTTGAGTGTTGAGT",
				"AAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAGAGGGAAGAGGGAAGAAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAAGAGGGAAGAGGGGAGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGGGAGGGGGGGAAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAAGAGGGAAGAGGGGAGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGGGAAGAGGGGAAAGAGGGAAGAGGGGAGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGGGAGGGGGGGAAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAAGAGGGAAGAGGGGAGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAGAGGGAAGAGGGAAGAGGGAAGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGGGAAAGAGGGAAGAGGGGAGGGGAGGGGGGGAGGG",
				"AAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAGATCAATCAATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAGATCAATCAATCATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAGATCAATCAATCAAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAGATCAATCAATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAGATCAATCAATCATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGAAGATCAAAGAAGAAGATCAAGAAGATCAAAGAAGAAGATCAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAAGAAGATCAATCAATCAAAGATCAATCAATCAAAGATCAATCAATCA",
				"AAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTAAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAGAGTACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAAAAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTAAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAGAGTACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAGAGTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAGAGTACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAGAGTACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAGAGTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAGAGTACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAAATACATGTTTGAAGTAAATACATGTTTGAAGTACTTAATGACGCAAGCTTAATGACGCAAGATGACGCAAGCTTAATGACGCAAGAG"
				}; 


	}

//	/**
//	 * MAIN TEST
//	 */
//	//@Test
//	public void basic() {
//		try {
//			int cnt=0;
//			for(String filePath : listOfPaths) {
//				System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
//				System.out.println("********basic******** Testing file: " + filePath);
//				String[] strArry = new String[] {filePath};
//				String[] dnaStrings = Basic.parseStrings(strArry);
//
//				double beforeUsedMem=Basic.getMemoryInKB();
//				double startTime = Basic.getTimeInMilliseconds();
//
//				Basic algo = new Basic(dnaStrings[0].toCharArray(),dnaStrings[1].toCharArray(),Basic.initAlphaTableMap(),30);
//				double afterUsedMem = Basic.getMemoryInKB();
//				double endTime = Basic.getTimeInMilliseconds();
//				double totalUsage = afterUsedMem-beforeUsedMem;
//				double totalTime = endTime - startTime;
//				String dnaSeqA = algo.getDnaA();
//				String dnaSeqB = algo.getDnaB();
//				//System.out.println("A :" + dnaSeqA);
//				//System.out.println("B :" + dnaSeqB);
//				//algo.printArray();
//				algo.printOptVal();
//				algo.printdnaAOut();
//				algo.printdnaBOut();
//				System.out.println(String.valueOf(totalTime));
//				System.out.println(String.valueOf(totalUsage));
//				//gapCounterTest();
//				assertEquals("DNA A", dnaA[cnt], dnaSeqA);
//				assertEquals("DNA B", dnaB[cnt], dnaSeqB);
//				System.out.println("=================================================");
//				cnt++;
//			}
//		}
//		catch(FileNotFoundException fnf) {
//			System.out.println("File not FOUND");
//			fnf.printStackTrace();
//		}
//		catch(Exception ee) {
//			System.out.println("There was a fail in the basic");
//			ee.printStackTrace();
//		}
//
//	}
//
//	//=========================================================================================================================================================
//
//	//@Test
//	public void efficient() {
//		try {
//			int cnt=0;
//			for(String filePath : listOfPaths) {
//				System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
//				System.out.println("********efficient******** Testing file: " + filePath);
//				String[] strArry = new String[] {filePath};
//				String[] dnaStrings = Basic.parseStrings(strArry);
//
//				double beforeUsedMem=Basic.getMemoryInKB();
//				double startTime = Basic.getTimeInMilliseconds();
//
//				Efficient algo = new Efficient(dnaStrings[0].toCharArray(),dnaStrings[1].toCharArray(),Basic.initAlphaTableMap(),30);
//				double afterUsedMem = Basic.getMemoryInKB();
//				double endTime = Basic.getTimeInMilliseconds();
//				double totalUsage = afterUsedMem-beforeUsedMem;
//				double totalTime = endTime - startTime;
//				//String dnaSeqA = algo.getDnaA();
//				//String dnaSeqB = algo.getDnaB();
//				//System.out.println("A :" + dnaSeqA);
//				//System.out.println("B :" + dnaSeqB);
//				//parsedFile.printArray();
//				algo.printOptVal();
//				//algo.printdnaAOut();
//				//algo.printdnaBOut();
//				System.out.println(String.valueOf(totalTime));
//				System.out.println(String.valueOf(totalUsage));
//				//assertEquals("DNA A", dnaA[cnt], dnaSeqA);
//				//assertEquals("DNA B", dnaB[cnt], dnaSeqB);
//				System.out.println("=================================================");
//				cnt++;
//			}
//		}
//		catch(FileNotFoundException fnf) {
//			System.out.println("File not FOUND");
//			fnf.printStackTrace();
//		}
//		catch(Exception ee) {
//			System.out.println("There was a fail in the efficient");
//			ee.printStackTrace();
//		}
//
//	}
	@Test
	public void both() throws IOException {
		int rowCnt = 1;
		int m_n_column = 0;
		int EffOptVal_column = 1;
		int EffTime_column = 2;
		int EffUtilization_column = 3;
		int BasicOptVal_column = 4;
		int BasicTime_column = 5;
		int BasicUtilization_column = 6;
		double afterUsedMem = 0;
		double endTime = 0;
		double totalUsage = 0;
		double totalTime = 0;
		double beforeUsedMem = 0;
		double startTime = 0;
		//Create Excel Workbook
		writeXLSX writeToExcel = new writeXLSX("output/excelOut_sampletescases1.xlsx");
		//writeXLSX writeToExcel = new writeXLSX("output/excelOut_datapoints24.xlsx");

		//Setup Excel column names
		setExcelHeader(writeToExcel);

		try {
			for(String filePath : listOfPaths)
			{
				System.out.println("********efficient******** Testing file: " + filePath);
				String[] strArry = new String[] {filePath};
				String[] dnaStrings = Basic.parseStrings(strArry);

				System.gc();

				beforeUsedMem= getMemoryInKBDouble();
				startTime = getTimeInMillisecondsDouble();

				Efficient algo = new Efficient(dnaStrings[0].toCharArray(),dnaStrings[1].toCharArray(),Basic.initAlphaTableMap(),30);

				afterUsedMem = getMemoryInKBDouble();

				endTime = getTimeInMillisecondsDouble();

				totalUsage = afterUsedMem - beforeUsedMem;
				totalTime = endTime - startTime;

				algo.printOptVal();
				algo.printdnaAOut();
				gapCounter(algo.getDnaAOut());
				algo.printdnaBOut();
				gapCounter(algo.getDnaBOut());

				System.out.printf("Total Time: %f ms\r\n", totalTime);
				System.out.printf("Before Memory Usage: %f KB\r\n", beforeUsedMem);
				System.out.printf("After Memory Usage: %f KB\r\n", afterUsedMem);
				System.out.printf("Total Utilization: %f KB\r\n", totalUsage);

				writeToExcel.writeInt(rowCnt,m_n_column,dnaStrings[0].length() + dnaStrings[1].length());
				writeToExcel.writeInt(rowCnt, EffOptVal_column, algo.getOptVal());
				writeToExcel.writeDouble(rowCnt, EffTime_column, totalTime);
				writeToExcel.writeDouble(rowCnt, EffUtilization_column, totalUsage);

				System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");

				//Need to free the object?
				algo = null;
				beforeUsedMem = 0;
				afterUsedMem = 0;
				startTime = 0;
				endTime = 0;
				totalUsage = 0;
				totalTime = 0;


				System.out.println("********basic******** Testing file: " + filePath);

				System.gc();
				beforeUsedMem=getMemoryInKBDouble();
				startTime = getTimeInMillisecondsDouble();
				
				Basic algo1 = new Basic(dnaStrings[0].toCharArray(),dnaStrings[1].toCharArray(),Basic.initAlphaTableMap(),30);

				afterUsedMem = getMemoryInKBDouble();

				endTime = getTimeInMillisecondsDouble();

				totalUsage = afterUsedMem - beforeUsedMem;
				totalTime = endTime - startTime;

				algo1.printOptVal();
				algo1.printdnaAOut();
				gapCounter(algo1.getDnaAOut()); 
				algo1.printdnaBOut();
				gapCounter(algo1.getDnaBOut());

				System.out.printf("Total Time: %f ms\r\n", totalTime);
				System.out.printf("Before Memory Usage: %f KB\r\n", beforeUsedMem);
				System.out.printf("After Memory Usage: %f KB\r\n", afterUsedMem);
				System.out.printf("Total Utilization: %f KB\r\n",totalUsage);

				writeToExcel.writeInt(rowCnt, BasicOptVal_column, algo1.getOptVal());
				writeToExcel.writeDouble(rowCnt, BasicTime_column, totalTime);
				writeToExcel.writeDouble(rowCnt, BasicUtilization_column, totalUsage);
				System.out.println("=================================================");

				algo1 = null;

				beforeUsedMem = 0;
				afterUsedMem = 0;
				startTime = 0;
				endTime = 0;
				totalUsage = 0;
				totalTime = 0;

				//cleanup
				System.gc();

				rowCnt++;
			}

			writeToExcel.close();
		}
		catch(FileNotFoundException fnf) {
			System.out.println("File not FOUND");
			fnf.printStackTrace();
		}
		catch(Exception ee) {
			System.out.println("There was a fail in the efficient");
			ee.printStackTrace();
		}
	
	}

	private static void setExcelHeader(writeXLSX excelWriter) {
		//N, EffOptVal, EffTime, EffUtilization, BasicOptVal, BasicTime, BasicUtilization

		excelWriter.writeString(0, 0, "M+N");
		excelWriter.writeString(0, 1, "EffOptVal");
		excelWriter.writeString(0, 2, "EffTime");
		excelWriter.writeString(0, 3, "EffUtilization");
		excelWriter.writeString(0, 4, "BasicOptVal");
		excelWriter.writeString(0, 5, "BasicTime");
		excelWriter.writeString(0, 6, "BasicUtilization");

	}

	private static long getMemoryInKB() {
		long total = Runtime.getRuntime().totalMemory();
		System.out.printf("Total Memory: %d\r\n",total);
		return (long) ((total - Runtime.getRuntime().freeMemory()) / 1E+3);
	}
	private static long getTimeInMilliseconds() {
		return (long) (System.nanoTime()/1E+6);
	}

	public static double getMemoryInKBDouble()
	{
		double total = Runtime.getRuntime().totalMemory();
		return (total - Runtime.getRuntime().freeMemory()) / 10E+3;
	}
	public static double getTimeInMillisecondsDouble()
	{
		return (double) (System.nanoTime()/10E+6);
	}

//=========================================================================================================================================================
	
	public static void gapCounterTest() {

		String[] gaps = {
				"_ACTG",
				"TAC_G",
				"_A_CA_CACT__G__A_C_TAC_TGACTG_GTGA__C_TACTGACTGGACTGACTACTGACTGGTGACTACT_GACTG_G",
				"ACAC___ACT_GAC_T_AC_TGAC_TGG_TGACT_ACTGAC_T_GGAC_T_GA_CTA_C_TGACTG_GTGAC_TACTGACTGG",
				"TATTATTA_TACGCTATTATACGCGAC_GCG_GACGCGTA_T_AC__G_CT_ATTA_T_AC__GCGAC_GC_GGAC_GCG",
				"__TATTATTATACGCTATTATACGCGACGC__GGAC_G_CGTATA_CGCTATTATACGCGA_C__GCG__GACG_C______G",
				"ACACACTGACTACTGACTGGTGACTACTGACTGGACTGACTACTGACTGGTGACTAC_TGACTG_G",
				"__________T__T_A_T__T_A_TAC_G_C__GAC_G____C_GA_T__T_A_TACGCGAC_GCG",
				"_A_A_A_A_A_A_GTCGTCA_GTCGTCA_A_GTCGTCA_GTCGTCA_A_A_GTCGTCA_GTCGTCA_A_GTCGTCA_GTCGTCA_A_A_A_GTCGTCA_GTCGTCA_A_GTCGTCA_GTCGTCA_A_A_GTCGTCA_GTCGTCAAGT_CGTCAGT_CGTC_",
				"TATATATATATACG_CGT_ACG_CGT_ATACG_CGT_ACG_CGT_ATATACG_CGT_ACG_CGT_ATACG_CGT_ACG_CGT_ATATATACG_CGT_ACG_CGT_ATACG_CGT_ACG_CGT_ATATACG_CGT_ACG_CGT__A_TACG_C_GTACG_CG",
				"TCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG_TCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGAA",
				"TCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG_A",
				"ACACACA______A_____A____A______A____CA_CA__CA____A__A_ACAC_ACACAAAAA_CACACAAAAC_ACACAAACACACAACAC_A_CACACACGTACGACG__TACGTTGTACGACGTA__CG_TTACGTACGACGTACGTTG_TACGACGTA__CG_TTGTACGACGTA__CGTTGTACGACG_TACGT_TACGTACGACGTACG_TTGTACGACGTACGTTC_ACACGTACGACGTACG_TTGTACGACGTA__CG_TTA_CGTACGACGTA__CG_TTGTACGACGTACGTTG_TACGACGTA__CG_TTGTACGACGTACGTTACGTACG_ACG_TA___CGTTGTACGACGTACGTTCACA_CACACACGTACGACG_TACGTTGTACGACGTACGT_TACGT_ACGACG__TACGTTGTACGACGTA__CG_TTGTACGACGTACGTTG_TACGACGTA__CG_TTACGTACGACGTA__CGTTGTACGACG_TACGTTCACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG_TTCA___CA_CA_ACAC_ACAC_A_CACGTACGACGTACGTTG_TACGACGTA__CG__T_TACGT_ACGACG__TACGTTGTACGACGTA__CG_TTGTACGACGTACGTTG_TACGACGTA__CG_TTACGTACGACGTA__CGTTGTACGACG_TACGTTCACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGT_TCA__CA___CA_CACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGTTCA___CA_CGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGTTCA_CA__CA____A__ACACACAACAC_A_CACACACGTACGACG_TACGTTGTACGACGTACGT_TACGT_ACGACG__TACGTTGTACGACGTA__CG_TTGTACGACGTACGTTG_TACGACGTA__CG_TTACGTACGACGTA__CGTTGTACGACG_TACGTTCACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGT_TCA__CA___CA_CACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGTTCA___CA_CGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG_TTCA___CA_CA_ACAC_ACAC_A_CACGTACGACGTACGTTG_TACGACGTA__CG__T_TACGT_ACGACG__TACGTTGTACGACGTA__CG_TTGTACGACGTACGTTG_TACGACGTA__CG_TTACGTACGACGTA__CGTTGTACGACG_TACGTTCACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGT_TCA__CA___CA_CACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGTTCA___CA_CGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTACGT_TACA_CA____A__ACACACAACAC_A_CACACACGTACGACG_TACGTTGTACGACGTACGT_TACGT_ACGACG__TACGTTGTACGACGTA__CG_TTGTACGACGTACGTTG_TACGACGTA__CG_TTACGTACGACGTA__CGTTGTACGACG_TACGTTCACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGT_TCA__CA___CA_CACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGTTCA___CA_CGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG_TTCA___CA_CA_ACAC_ACAC_A_CACGTACGACGTACGTTG_TACGACGTA__CG__T_TACGT_ACGACG__TACGTTGTACGACGTA__CG_TTGTACGACGTACGTTG_TACGACGTA__CG_TTACGTACGACGTA__CGTTGTACGACG_TACGTTCACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGT_TCA__CA___CA_CACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGTTCA___CA_CGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGTTCA_CA__CA____A__ACACACAACAC_A_CACACACGTACGACG_TACGTTGTACGACGTACGT_TACGT_ACGACG__TACGTTGTACGACGTA__CG_TTGTACGACGTACGTTG_TACGACGTA__CG_TTACGTACGACGTA__CGTTGTACGACG_TACGTTCACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGT_TCA__CA___CA_CACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGTTCA___CA_CGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG_TTCA___CA_CA_ACAC_ACAC_A_CACGTACGACGTACGTTG_TACGACGTA__CG__T_TACGT_ACGACG__TACGTTGTACGACGTA__CG_TTGTACGACGTACGTTG_TACGACGTA__CG_TTACGTACGACGTA__CGTTGTACGACG_TACGTTCACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGT_TCA__CA___CA_CACACGTACGACGTACG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CGTTCA___CA_CGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTA__CG____TTGTACGACGTA__CG_TTGTACGACGTACGT__TACGTACGACGTACG_TTGTACGACGTACGTT_",
				"_T_T_TATTTTTTATTTTTATTTTATTTTTTATTTTTATTATTTATTTTATTATACGCGACGC___GATTATAC___GCGACGC_GATACGCGACGCGATTATACGCG_ACG_CGTTTA__TTATACG_CG_ACGCGATTA__TACG_CG_ACG_CGATACG_CG_ACGCGATTATACG_CG_ACGCGTT_TAT__T_TTAT_TATACG__CGACG__CGATTATACG_CG_ACG__CGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACG_CGATACG_CG_ACGCGATTATACG_CG_ACG___CGTAT_TAT_TTATTTTATTATACG_CG_ACG__CG_ATTATACGCG_ACG_CGATACG_CG_ACG_CG_AT_TATACGCGACG_CGTTTA__TTATACG_CG_ACGCGATTATACG_CG_ACG_CGATACG_CG_ACGCGATTA__TACG_CG_ACGCGTT_TAT__T_TTA__TT_ATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGATTTATTTTATTATACGCGACGCGATTA__TACG_CG_ACG_CGATACG_CG_ACGCGATTATACGCGACG_CGTTTA__TTATACG_CG_ACGCGATTATACG_CG_ACG_CGATACG_CG_ACGCGATTA__TACG_CG_ACGCGTT_TAT__T_TTA__TT_ATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTATTATTTATTTTATTATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTT_ATTATTTATTTTATTATACGCGACGCGATTATACGCG_ACG_CGATACG_CG_ACG_CG_AT_TATACGCGACG_CGTTTA__TTATACG_CG_ACGCGATTATACG_CG_ACG_CGATACG_CG_ACGCGATTA__TACG_CG_ACGCGTT_TAT__T_TTA__TT_ATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTATTATTTATTTTATTATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGATTTATTTTATTATACGCGACGCGATTA__TACG_CG_ACG_CGATACG_CG_ACGCGATTATACGCGACG_CGTTTA__TTATACG_CG_ACGCGATTATACG_CG_ACG_CGATACG_CG_ACGCGATTA__TACG_CG_ACGCGTT_TAT__T_TTA__TT_ATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTATTATTTATTTTATTATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTAT_TTATTTTATTATACGCGACGCGATTATACGCG_ACG_CGATACG_CG_ACG_CG_AT_TATACGCGACG_CGTTTA__TTATACG_CG_ACGCGATTATACG_CG_ACG_CGATACG_CG_ACGCGATTA__TACG_CG_ACGCGTT_TAT__T_TTA__TT_ATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTATTATTTATTTTATTATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGATTTATTTTATTATACGCGACGCGATTA__TACG_CG_ACG_CGATACG_CG_ACGCGATTATACGCGACG_CGTTTA__TTATACG_CG_ACGCGATTATACG_CG_ACG_CGATACG_CG_ACGCGATTA__TACG_CG_ACGCGTT_TAT__T_TTA__TT_ATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTATTATTTATTTTATTATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTT_ATTATTTATTTTATTATACGCGACGCGATTATACGCG_ACG_CGATACG_CG_ACG_CG_AT_TATACGCGACG_CGTTTA__TTATACG_CG_ACGCGATTATACG_CG_ACG_CGATACG_CG_ACGCGATTA__TACG_CG_ACGCGTT_TAT__T_TTA__TT_ATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTATTATTTATTTTATTATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGATTTATTTTATTATACGCGACGCGATTA__TACG_CG_ACG_CGATACG_CG_ACGCGATTATACGCGACG_CGTTTA__TTATACG_CG_ACGCGATTATACG_CG_ACG_CGATACG_CG_ACGCGATTA__TACG_CG_ACGCGTT_TAT__T_TTA__TT_ATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTATTATTTATTTTATTATACG__CGACG__CGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACGCGTTTATTATACG_CG_ACGCGATTATACG_CG_ACGCGATACG__CGACG__CGATTATACG_CG_ACG_CG"
				};

		for(String s:gaps)
		{
			gapCounter(s);
		}

	}

	public static void gapCounter(String s)
	{
		int retVal = 0;
		for(int i = 0; i < s.length(); i++)
		{
			if(s.charAt(i) == '_')
				retVal++;
		}

		System.out.printf("Number of Gaps: %d\r\n", retVal);
	}

	public static int gapCounters(String s)
	{
		int retVal = 0;
		for(int i = 0; i < s.length(); i++)
		{
			if(s.charAt(i) == '_')
				retVal++;
		}

		return retVal;
	}

	/**
	 * Need main for MacOS
	 * @param args - possibly input string
	 * @throws Exception - file not found
	 */
//	public static void main(String[] args) throws Exception {
//		setUp();
//		both();
//	}


	@Test
	public void countStrings() {
		String eff1_1_grader = "ATATCCATATATCCATATATCCATATATCCATATCCATATATCCA_TATATCCATATATCCATCCA_TATATCCATATATCCATATATCC_A_TATATCCAATATCC_A_TATATCCA_TATATCCATATAT_CC_A_TATAT_CC_A_TATA_T_CCATA_TATCCATATCCATA_TATCCA_TATATCCATATATCCATCCATA_TATCCATATATCCATA_TATCCA_TATATCCAATATCCA_TATATCCATA_TATCCATA_TATCCATATCCATA_TATCCA_TATATCCATATATCCATCCATA_TATCCATATATCCATA_TATCCA_TATATCCATATAT_CCAT_CCATATATCCATATATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCCC_CCAT_CC_CCATATCCATCCCCCCATCCCCCCATCC_CC_CCATCCCCATCCATATATCCATATCCATCCCCCCATCCCC_CCAT_CC_CCCCATCCCCATATCCATCC_CCC_C_ATCC_CC_CCATCCCC_CCATCCCC_CCATA_TATCCA_TATATCCATATATCCA_TATATCCATATAT_CCAT_CCATATATCCATATATCCATA_TATCCATATCCATCCCC_CCATCCCC_CCATCCC_CCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCC_CCATCC_CCATCCA_TATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCC_CCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCC_CCA_TATATCCATA_TATCCATA_TATCCATATCCATA_TATCCA_TATATCCATATATCCATCCATATATCCATATATCCATATATCCATA_TATCCATA_TATCCAT_CCATA_TATCCA_TATATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCCCCATC_CCCATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCCC_CCAT_CC_CCATATCCATCCCCCCATCCCCCCATCC_CC_CCATCCCC_CCATATATCCA_TATATCCATATATCCA_TATATCCATATAT_CCAT_CCATATATCCATATATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCCC_CCAT_CC_CCATATCCATCCCC_CCATCC_CC_CCATCCCC_CCATCCCCAT_CC_A_TATA_T_CCATATCCATCCCC_CCATCC_CC_CCATCCCC_CCAT_CC_CCATATCCATCCCCCCATCCCCCCATCC_CC_CCATCCC_CTATATCCATCCATATATCCATATATCC_A_TATA_T_CCATATCCATCCCC_CCATCC_CC_CCATCCCC_CCAT_CC_CCATATCCATCCCCCCATCCCCCCATCC_CC_CCATCCCCATCCATATATCCATATCCATCCCCCCATCCCC_CCAT_CC_CCCCATCCCCATATCCATCC_CCC_C_ATCC_CC_CCATCCCC_CCATCCCC_CCATA_TATCCA_TATATCCATATATCCA_TATATCCATATAT_CCAT_CCATATATCCATATATCCATA_TATCCATATCCATCCCC_CCATCCCC_CCATCCC_CCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCC_CCATCC_CCATCCA_TATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCC_CCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCC_CCA_TATATCCATA_TATCCATA_TATCCATATCCATA_TATCCA_TATATCCATATATCCATCCATATATCCATATATCCATATATCCATA_TATCCATA_TATCCAT_CCATA_TATCCA_TATATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCCCCATC_CCCATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCCC_CCAT_CC_CCATATCCATCCCCCCATCCCCCCAT_CC_CCCCATCCCC_CCATATATCCA_TATATCCATATATCCA_TATATCCATATAT_CCAT_CCATATATCCATATATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCCC_CCAT_CC_CCATATCCATCCCCCCATCCCCCCATCC_CC_CCATCCCCATCCATATATCCATATCCATCCCCCCATCCCC_CCAT_CC_CCCCATCCCCATATCCATCCCCCCATCCCC_CCATCC_CC_CCATCCCCA_TATCCATATCCATA_TATCCA_TATATCCATATATCCATCCATATATCCATATATCCATATATCCATA_TATCCATA_TATCCAT_CCATA_TATCCA_TATATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCCCCATC_CCCATCCATA_TATCCATATCCATCCCC_CCATCCCC_CCATCCC_CCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCC_CCATA_TATCCA_TATATCCATATATCCA_TATATCCATATAT_CCAT_CCATATATCCATATATCCATA_TATCCATATCCATCCCC_CCATCCCC_CCATCCC_CCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCC_CCATCC_CCATCCA_TATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCC_CCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCC_CCA_TATATCCATA_TATCCATA_TATCCATATCCATA_TATCCA_TATATCCATATATCCATCCATATATCCATATATCCATATATCCATA_TATCCATA_TATCCAT_CCATA_TATCCA_TATATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCCCCATC_CCCATCCATA_TATCCATATCCATCCCC_CCATCCCC_CCATCCC_CCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCC_CCATA_TATCCA_TATATCCATATATCCA_TATATCCATATATCCATCCATATATCCATATATCCA_TATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCC_CCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATCCA_TATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCTATATCCATCCATATATCCATATATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCCCCATCCCCCCA_TATATCCATATATCCATATATCCATA_TATCCATA_TATCCAT_CCATA_TATCCA_TATATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCCCCATC_CCCATCCATA_TATCCATATCCATCCCC_CCATCCCC_CCATCCC_CCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCCCATATATCCATA_TATCCA_TATATCCATATCCATATATCCATATATCCATATATCCATCCATATATCCATATATCCATATATCCATA_TATCCATA_TATCCAT_CCATA_TATCCA_TATATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCCCCATC_CCCATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCCC_CCAT_CC_CCATATCCATCCCCCCATCCCCCCATCCCC_CCATCCC_CCCA_TATATCCA_TATATCCATATATCC_A_TATA_T_CCATA_TATCCAT_CCATA_TATCCA_TATATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCCCCATC_CCCATCCATA_TATCCATATCCATCCCC_CCATCCCC_CCATCCC_CCCATCCCCATATCCATCCCCCCATCCCC_CCATCCCC_CCAT_CC_CC";
		String eff1_2_grader = "_TA_C__T_TA_CTATAT_TTT_T_TA_CT_TA_CTATAT_TTTACT_TA_C__TATATTT_TTTACT_TA_C__TATATTT_T_TA_CTTACTATATTT__TA_CTTACTATATTTACT_TA_CTATAT_TACTTACTATATACTTACTATACTACCATACTACCC_TA_CCATACTA_CCACT_TA__C_TATA_CTA_CCATACTA_CC_C_TA_CCATACTA_CCACT_TA_CT_ATAT__ACT_TA_CTATACTA_CCATACTACCC_TA_CCATACTA_CCACT_TA_C__TATA_CTA_CCATACTA_CC_C_TA_CCATACTA_CCACT_TA_CTATAT_TACT_TACTATATA_C__T_TA_CTATACTA_CCATA_CTA_CCCTACCAT__ACTACCA_C_TTACTATACTACCATA_CTA___CCCTA_____CCAT__ACTACCA_C_TTA_CTATATA_CT_TA_CTAT______A___CTACCATACTACCCTA___CCATA_CTA_CCACTTACTAT__ACTACCAT____ACTA_CCCTACCATACTA_CCACT_TA_C__TATATTTACT_TA_CTATAT_TACT_TACTATATA_C__T_TA_CTATACTA_CCATA_CTA_CCCTACCAT____ACTA_C_CACTTA___CTATA_CTA_____CCAT____ACTA_CCCTACCAT__ACTA_CCACT_TA_CTATAT__A_C___TTA_____CTAT______A_CTACCATA_CTA___CCCTA_____CCAT______A___CTACCACT_TA_CTATACTA_CCATACTACCC_TA_CCATACTA_CCACT_TA_C__TATATT_A_C__T_TA_CTATATA_C__T_TA_CTATACTA_CCATACTACCC_TACCATACTA_CCACT_TA_C__TATA_C__TA_CCAT______A_____CTA___CCCTA___CCATA_CTA_____CCA_C_TTACTAT______AT_ACTTA_CTATACTA_CCATA_CTA_CCCTACCAT__ACTACCA_C_TTACTATACTACCATA_CTA___CCCTA_____CCAT__ACTACCA_C_TTACTATAT_TTTACT_TA_C__TATATTTACT_TA_CTATAT_TACT_TACTATATA_C__T_TA_CTATACTA_CCATA_CTA_CCCTACCAT__ACTACCA_C_TTACTATACTACCATA_CTA_CCCTACCAT__ACTACCA_C_TTACTAT____ATACTTACTATACTACCATA_CTA_CCCTACCAT__ACTACCA_C_TTACTATACTACCATA_CTA___CCCTA_____CCAT__ACTACCA_CTTACTATAT_TA__C_T_TA_CTATATA_CTTACTATACTACCATA_CTA_CCCTACCAT__ACTACCA__CTTACTATACTACCATA_CTA_C__CCTA____C_CAT__ACTACCA__CTTA_CTATATA_CT_TA_CTAT______A_C__TACCATACTACCCTA_C__CATA_CTA_CCACTTACTAT__ACTACCAT____ACTA_CCCTACCATACTA_CCACT_TA_C__TATATTTACT_TA_CTATAT_TACT_TACTATATA_C__T_TA_CTATACTA_CCATA_CTA_CCCTACCAT____ACTA__CCACTTA__C_TATA_CTA__C___CAT____ACTA_CCCTACCAT__ACTA_CCACT_TA_CTATAT__A____CTTA__C___TAT______A_CTACCATA_CTA__C_CCTA__C___CAT______A__C_TACCACT_TA_CTATACTA_CCATACTACCC_TA_CCATACTA_CCACT_TA_C__TATAT_TA_C__T_TA_CTATATA_C__T_TA_CTATACTA_CCATACTACCC_TACCATACTA_CCACT_TA_C__TATA_C__TA_CCAT______A__C___TA__C_CCTA__C_CATA_CTA__C___CA__CTTACTAT______AT_ACTTA_CTATACTA_CCATA_CTA_CCCTACCAT__ACTACCA__CTTACTATACTACCATA_CTA__C_CCTA__C___CATACTACCTTA__CTTACTATAT_TTTACT_TA__C_TATATTTACT_TA_CTATAT_TACT_TACTATATA__C_T_TA_CTATACTA_CCATA_CTA_CCCTACCAT__ACTACCA__CTTACTATACTACCATA_CTA_C__CCTA____C_CAT__ACTACCA__CTTA_CTATATA_CT_TA_CTAT______A_C__TACCATACTACCCTA_C__CATA_CTA____C_CA__CTTACTAT__ACTACCAT____ACTACCC_TA_CCATACTA_CCACT_TA__C_TATAT_TA__C_T_TA_CTATATA__C_T_TA_CTATACTA_CCATACTACCC_TACCATACTA_CCACT_TA__C_TATA__C_TA_CCAT______A____C_TA_C__CCTA_C__CATA_CTA____C_CA__CTTACTAT______AT_ACTTA_CTATACTA_CCATA_CTA_CCCTACCAT____ACTA__CCACTTA_C__TATA_CTA____C_CAT______A____C_TA_CCCTACCATACTA_CCACT_TA_C__TATATTTACT_TA_CTATAT_TACT_TACTATATA_C__T_TA_CTATACTA_CCATA_CTA_CCCTACCAT____ACTA__CCACTTA__C_TATA_CTA__C___CAT____ACTA_CCCTACCAT__ACTA_CCACT_TA_CTATAT__A____CTTA__C___TAT______A_CTACCATA_CTA__C_CCTA__C___CAT______A__C_TACCACT_TA_CTATACTA_CCATACTACCC_TA_CCATACTA_CCACT_TA_C__TATAT_TA_C__T_TA_CTATATA_C__T_TA_CTATACTA_CCATACTACCC_TACCATACTA_CCACT_TA_C__TATA_C__TA_CCAT______A__C___TA__C_CCTA__C_CATA_CTA__C___CA__CTTACTAT______AT_ACTTA_CTATACTA_CCATA_CTA_CCCTACCAT____ACTA__CCACTTA__C_TATA_CTA__C___CAT______A__C___TA_CCCTACCATACTA_CCACT_TA_CTATAT_TTTACT_TA__C_TATATTTA__C_T_TA__C_TATAT_TACT_TA_CTATAT__A____CTTA____C_TAT______A_CTACCATA_CTA_C__CCTA____C_CAT______A_C__TA_CCACT_TA_CTATA_CTA____C_CAT______A____C_TA__CCC_TA_CCAT______A____C_TA____C_CA____CT_TA_C__T__ATATA_C__T_TA_C__TATA_C__TA_CCAT______A_____C__T______A_C_CC_TA_CCAT______A_____CTA_____CCA_C_TTA_C__TATA_C__TA_CCAT______A_____CTA___CCCTA___CCATA_CTA_____CCA_C_TTACTAT______AT____T_ACT_TA_CTATATA_C__T_TA_CTATACTA_CCATACTACCC_TACCATACTA_CCACT_TA_C__TATA_C__TA_CCAT______A_____CTA___CCCTA___CCATA_CTA_____CCA_C_TTACTAT______AT_ACTTA_CTATACTA_CCATA_CTA_CCCTACCAT____ACTA_C_CACTTA___CTATA_CTA_____CCAT______A_____CTA___C_CC_T__A_CCATACTA_CCACT_TA_CTATAT___T_TA_C__T_TA_C__TATATT_A_C__T_TA_CTATATA_C__T_TA_CTATACTA_CCATACTACCC_TACCATACTA_CCACT_TA_C__TATA_C__TA_CCAT______A_____CTA___CCCTA___CCATA_CTA_____CCA_C_TTACTAT______AT_ACTTA_CTATACTA_CCATA_CTA_CCCTACCAT__ACTACCA_C_TTACTATACTACCATA_CTA___CCCTA_____CCAT____ACTA_C_CACTTACTATATT_ACT_TA_CTATATA_CTTACTATACTACCATACTACCC_TACCATACTA_CCACT_TA_C__TATA_C__TA_CCAT______A_____CTA___CCCTA___CCATA_CTA_____CCA_C_TTACTAT______AT_ACTTA_CTATACTA_CCATA_CTA_CCCTACCAT____ACTA_C_CACTTA___CTATA_CTA_____CCAT____ACTA_CCCTACCATACTACC";

		String eff1_1_group = "_A_TA_TCCATATATCCATATATC__CATATATCCATATCCATATATCCATATATCCATATATC_CATCCATA_TATCCA_TATATCCATATATC_CATATATCCAATATCCA_TATATCCATATA_T__CC_ATATATCCATATATCCA_TATATCCATA_TATCCATATCCA_TATATC_CATATATCCATATATCCATCCATA_TATCCATATATCCA_TATATC_CATATATCCAAT_ATCCATATATCCATA_TATCCATATA_TCCATATCCATA_TATCCA_TATATCCATATATCCATCCATATA_TCCATATATCCATA_TATCCA_TATATCCATA_TA_TCCATCCATATATCCATATATCCATATA_TCCATATCCATCCCCCC__AT_CCCCCCATCCCCC_CA_T_CCCCATATCCATCCCCCC__ATCCCCCCATCCCCCCATCCCCATCCATATATCCATATCCAT_CC_CCCCATCC_CC_CCATCCCCCCAT_CCCCATATCCATC_CCCCCAT_CC_CCCCATCC_CC_CCATCCCCCCA_TATATC_CATATATCCATATAT_CCATATATCCATATA_TC_CATCCATATATCCATATATCCA_TATATCCATATCCATCC_CCCCAT_CC_CCCCATC_CCCCCAT_CC_CCATATCCATCC_CCCCAT_CCCCCCATCCCCCCATCCCCATCCATATATCCATATCCATCC_CC_CCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCCCATATATCCATA_TATCCATATA_TCCATATCCATA_TATCCA_TATATCCATATATCCATCCATATATCCATATATCCATATATCCATATA_TCCA_TATAT_CCATCCATATA_TCCA_TATATCCATATA_TCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCC_CATCCCCCCATCCCCCCATCCCCATCCA_TATATCCATATCCATCC_CCCCAT_CC_CCCCATC_CCCCCAT_CC_CCATATCCATCC_CCCCAT_CC_CCCCATCCCCCCATCCCCCCATATATCCA_TATATCCATATATC_CATATATCCA_TA_TATCCATCCATATATCCATATATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCC_CCCATCC_CC_ATATCCATCCCC_CCATCC_CC_CCATCCC_CCCATCCCCA_TC_CA_TATA_T_CCATATCCATCCCCCC__AT_CCCCCCATCCCCC_CA_T_CCCCATATCCATCCCCCC__AT_CCCCCCATCCCCCCATCCCCTATA_T_C_CATCCATATATCCATATATCCA_TATATCCATATCCATCC_CCCCAT_CC_CCCCATC_CCCCCAT_CC_CCATATCCATCC_CCCCAT_CCCCCCATCCCCCCATCCCCATCCATATATCCATATCCATCC_CC_CCA_T_CCCCCCATCCCCCCAT_CCCCATATCCATCCC_CCCATCC_CC_CCA_T_CCCCCCATCCCCCCATA_TATCCA_TATATCCATATATC_CATATATCCA_TA_TATCCATCCATATATCCATATATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCC_CCCATCC_CC_ATATCCATCCCC_CCATCC_CCCCATCCCCCCATCCCCATCCATATATCCATATCC_AT_CCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCCCATATATCCATATA_TCCA_TATATCCATATCCATATA_TCCA_TATATCCATATATCCATCCATATATCCATATATCCATATATCCA_TATATCCATA_TATCC_ATCCA_TATATC_CATATATCCA_TATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATC_CCCCCATCCCCCCATCCCCCCATCCCCATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCC_CCCATCC_CC_ATATCCATCCCC_CCATCC_CC_CCATCCCCCCATCCCCCCATATATC_CATATATCCATATAT_CCATATATCCATATA_TC_CATCCATATATCCATATATCCA_TATATCCATATCCATCC_CCCCAT_CC_CCCCATC_CCCCCAT_CC_CCATATCCATCC_CCCCAT_CCCCCCATCCCCCCATCCCCATCCATATATCCATATCCATCC_CC_CCA_TCCCCCCATCCCCCCATCCCCATATCCATCCCC_CCATCCCCCCATCC_CC_CCA_TCCCCATATCCATATCCATA_TATCCA_TATATCCATATATCCATCCATATATCCATATATCCATATATCCATATA_TCCA_TATAT_CCATCCATATA_TCCA_TATATCCATATA_TCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCC_CATCCCCCCATCCCCCCATCCCCATCCA_TATATCCATATCCATCC_CCCCAT_CC_CCCCATCCCCCCATCCCCATATCCATCCCCCCATCC_CCCCATCCCCCCATCCCCCCA_TATATC_CATATATCCATATAT_CCATATATCCATATA_TC_CATCCATATATCCATATATCCA_TATATCCATATCCATCC_CCCCAT_CC_CCCCATC_CCCCCAT_CC_CCATATCCATCC_CCCCAT_CCCCCCATCCCCCCATCCCCATCCATATATCCATATCCATCC_CC_CCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCCCATATATCCATA_TATCCATATA_TCCATATCCATA_TATCCA_TATATCCATATATCCATCCATATATCCATATATCCATATATCCATATA_TCCA_TATAT_CCATCCATATA_TCCA_TATATCCATATA_TCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCC_CATCCCCCCATCCCCCCATCCCCATCCA_TATATCCATATCCATCC_CCCCAT_CC_CCCCATCCCCCCATCCCCATATCCATCCCCCCATCC_CCCCATCCCCCCATCCCCCCA_TATATC_CATATATCCATATATCCA_TATATCCATATATCCATCCATATA_TCCATATATCCATATATCCATATCCATCCC_CCCATCCCCCCATCCCCCCATCCCCATATCCATCCCC_CCATCCCCCCATCCCCCCATCCCCATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCTATATCCATCCATATATCCATATATCCATATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATCCATATA_TCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATCCCCC_CATCCCCCCATCCCCCCATCCCCCCATATATCCATATATCCATATATCCA_TATATCCATA_TATCC_ATCCA_TATATC_CATATATCCA_TATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATC_CCCCCATCCCCCCATCCCCCCATCCCCATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCCCCCATCCCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCCCATATATCCATA_TATCCA_TATATCCATATCCATATATCCATATATCCATATATCCATCCATATATCCATATATCCATATATCCATA_TATCCATATA_TCC_ATCCATA_TATCCA_TATATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCCCCCATCCCCATATCCATCCCCC_CA_T_CCCCCCAT_CCCCCCATCCCCATCCATATA_TCCAT__ATCC_AT_CCCCCCAT_CCCCCCATCCCCCCATCCCCATATCCATC_CCCCCATCCCCCCATCCCCCCA_TCCCCCCATATATCCATATATCCATATATCCA_TATATCCATA_TATCC_ATCCA_TATATC_CATATATCCA_TATATCCATATCCATCCCCCCATCCCCCCATCCCCCCATCCCCATATCCATC_CCCCCATCCCCCCATCCCCCCATCCCCATCCATA_TATCCATATCCATCCCC_CCATCC_CC_CCATCCC_CCCATCC_CC_ATATCCATCCCC_CCATCCCCCCATCCCCCCATCCCC";
		String eff1_2_group = "TACTTAC_TATATT_TTT_TA_CTTAC_TATATTTT_A_CT__TA_C_TATATT_TTT_TA_CTTA_CT_ATATT_TTTACT_TACT_ATATTT_TACTTA_C_TAT_ATTTACT_TACT_ATATTACTTACTATATA_CT__TA_C_TATACTA_CCATACTACCCTA_C_CATACTA_CCACTTA_C_TA__TA_CTA_CCATACTACCCTA_C___CATACTA_CCACTTA_C_TATATAC_T__T_A_CTATACTACC_ATACTACCCT_A_CCATACTACC_ACTT_A_CT__ATACT_ACC_ATACTACCCT_A_C__CATACTACC_ACTT_A_CTATATTACTTA_C_TATATAC_T_T__ACT_ATACTAC_CATA_CTA_CCCTACCATACTACCA__C_TTACTA_TACTACCATA_CTA_CCCTACCATACTA____C_CA____C_TTA_CT_ATATA_CTTA_C_TATACTACCAT__ACTACCCTAC_CA____TACT____A_CCA_CTTACTA_TACTACCAT__ACTACCCTAC_CA____TACTA_CCACTTA_C_TATATT_TACT_T_ACT_ATATTACTTA_CT_ATATA_CT__TA_C_TATACTA_CCATACT_ACC_CTACCATACTACCA_C__TTACTA_TACTACCATACT_ACC_CTACCATACTA_C____CA_C____TTA_C_TATATACT_T_A_CTATACTACCA__T______AC_TA____C_CCT__A_CCATA______CT_A____CC_A____C_T______T_A_CTATACTACC_ATACTACCCT_A_CCATACTACC_ACTT_A_CTATAT_TA__C_T__T_A_CTATATAC_T_T__ACT_ATACTAC_CATACTACCCTACC_ATACTAC_CACT_TACT_ATACTAC_CATA_CTA_CCCTA__CC_A____T______AC_TA____C_CAC_TTACTA_T______ATA_C______TTA_C_TATACTA_CCATACT_ACC_CTACCATACTACCA_C__TTACTA_TACTACCATACT_ACC_CTACCATACTACCA_C__TTA___C_TA____TATT_TTACTT_A_CTATAT_TTACT_TA_C_TATATTACTTA_C_TATATAC_T__T_A_CTATACTACC_ATAC_TAC_CCTACCATACTACCA__CT_TACTAT_ACTACCATAC_TAC_CCTACCATACTACCA__CT_TACTAT_A____TACTTACTATACTACCATA_CTA_CCCTACCATACTACCA__C_TTACTA_TACTACCATA_CTA_CCCTACCATACTACCA__C_TTA___CT____ATATTACTTACT_ATATA_CT__TA_C_TATACTA_CCATACT_ACC_CTACCATACTACCA_C__TTACTA_TACTACCATACT_ACC_CTACCATACTA_C____CA_C____TTA_C_TATATACT_T_A_CTATACTACCA__TACTACCCTA_CCAT____AC_T___ACC_ACT_TACTAT_ACTACCA__TACTACCCTA_CCAT____ACTACC_ACTT_A_CTATAT_TTACT_TA_C_TATATTACTTA_C_TATATAC_T__T_A_CTATACTACC_ATAC_TAC_CCTACCATACTACCA__CT_TACTAT_ACTACCATAC_TAC_CCTACCATACTA____CC_A____CT_TA_C_TATATAC_T_TACT_ATACTACCA__TA_C______TA_C____CC_T_ACC_AT______AC_TA____C_CA____C_T_T______ACT_ATACTAC_CATACTACCC_TACC_ATACTAC_CACT_TACT_ATATT__A_C_T_T__ACT_ATATA_CT__TA_C_TATACTA_CCATACTACCCTAC_CATACTA_CCACTTA_C_TATACTA_CCATACT_ACC_CTA__C_CA____TA_C______T____A_CCA_CTTACTA_TAT______A______CT_TA_C_TATACTACC_ATAC_TAC_CCTACCATACTACCA__CT_TACTAT_ACTACCATAC_TAC_CCTACCATACTACCTTAC_TTA___CT_A____TATTT_TACTTA_C_TATATT_TACT_T_ACT_ATATTACTTA_CT_ATATA_CT__TA_C_TATACTA_CCATACT_ACC_CTACCATACTACCA_C__TTACTA_TACTACCATACT_ACC_CTACCATACTA_C____CA_C____TTA_C_TATATACT_T_A_CTATACTACCA__TACTA____C_CCTA_C__CAT__ACT_ACC_ACTTA_C_TAT____ACTACCA__TACTA____CCCT_A_CCATACTACC_ACTT_A_CTATAT_TA__C_T__T_A_CTATATAC_T_T__ACT_ATACTAC_CATACTACCCTACC_ATACTAC_CACT_TACT_ATACTAC_CATA_CTA_CCCTA__CC_A____T______AC_TA____C_CAC_TTACTA_T______ATA_C______TTA_C_TATACTA_CCATACT_ACC_CTACCATACTACCA_C__TTA___C_TA__TA_CTA_CCAT____ACTA____CC_CTA__C_CA____TACTA_CCACTTA_C_TATATT_TACT_T_ACT_ATATTACTTA_CT_ATATA_CT__TA_C_TATACTA_CCATACT_ACC_CTACCATACTACCA_C__TTACTA_TACTACCATACT_ACC_CTACCATACTA_C____CA_C____TTA_C_TATATACT_T_A_CTATACTACCA__T______AC_TA____C_CCT__A_CCATA______CT_A____CC_A____C_T______T_A_CTATACTACC_ATACTACCCT_A_CCATACTACC_ACTT_A_CTATAT_TA__C_T__T_A_CTATATAC_T_T__ACT_ATACTAC_CATACTACCCTACC_ATACTAC_CACT_TACT_ATACTAC_CATA_CTA_CCCTA__CC_A____T______AC_TA____C_CAC_TTACTA_T______ATA_C______TTA_C_TATACTA_CCATACT_ACC_CTACCATACTACCA_C__TTA___C_TA__TA_CTA_CCAT____ACTA____CC_CTA__C_CA____TACTA_CCACTTA_C_TATATT_TTACTT_A_CTATAT_TTA_C_TTA_CTATAT__T_A_CT__TA_C_TATATA__CT_TACTAT_A______CT_A____CC_A__TAC_TAC_CCTACCATA______CT_A____CC_A__C_T__T_A_CTATACT_ACC_A____T______AC_TA____C_CCT__A_CCATA______CT_A____CC_A____CT____T_A_CT__AT__ATAC_T_T__AC_T__ATAC_TA__C_CATA_C______TA_C____CCTA__CC_A__TAC_TAC_CA____C_T_T____A______C_T____A__TACTAC_CATA_CTA_CCCTA__CC_A____T______AC_TA____C_CAC_TTACTA_T______ATTA_____C_T_T______ACT_ATATA_CT__TA_C_TATACTA_CCATACTACCCTAC_CATACTA_CCACTTA_C_TATACTA_CCATACT_ACC_CTA__C_CA____TA_C______T____A_CCA_CTTACTA_TAT______A______CT_TA_C_TATACTACC_ATAC_TAC_CCTACCATACTACCA__CT_TA_C___TAT__ACT_ACC_A____T______AC_TA____C_CCT____A_C__CATACTACC_ACTT_A_CTATAT___TT_A_CT__TA_C_TATATT_A_C__T__TA_C_TATATAC_T__T_A_CTATACTACC_ATACTACCCTA_CCATACTACC_ACTT_A_CTATACTACC_ATAC_TAC_CCTACCATACTACCA__CT_TA_C___TAT__AT__AC_TTACTA_TACTACCA__TACTA_C____CCTACC_ATACTAC_CACTTACT_ATACTACCA__TACTA_C____CCTA__CC_A__TAC_TAC_CACTTA_CT_A____T______ATTACT_T_____ACT_ATATA_CT__TA_C_TATACTA_CCATACTACCCTAC_CATACTA_CCACTTA_C_TATACTA_CCATACT_ACC_CTA__C_CA____TA_C______T____A_CCA_CTTACTA_TAT______A______CT_TA_C_TATACTACC_ATAC_TAC_CCTACCATACTACCA__CT_TACTAT_ACTACCATAC_TAC_CCTACCATA______CT_A____CC___";

		String eff2_1_grader = "__A__CA_CGT__A___CA__CA_CGT__A__CA__CA_CGT__A________________________________________________________________________________________________________________________________________________________________C_AC____A___C_AC_A___C_AC__GTA_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC_A___C_AC__GTA_CAC_AC___G_TA_C____A__CA_CGTA_CAC_AC__GTA_CAC_AC__GTAC_AC____A_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC__GTACACAC__GTA___C_AC___G_T_GTGTACGT_GT_G_TACGTGTGTACG_T_GTGT_GTAC_AC__GT_GT_______GTAC_G__TGT_GTAC____G_T_GTGTA___C_G__TGT_GTAC_AC__GTACACAC__GTA___C_AC___G_T_GTGT__A__C_GTGT_GTAC_____GT_GTAC_AC__GTAC_AC____A___C____G_TA_C__A___C_AC__GTA___C_AC_A___C_AC____A___C_AC_G_TA__CA_________________________________C_AC__GTA_CAC_AC__GTAC_AC____A_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC__GTAC_AC____A___C______G_TA_C____A____________C_AC__GTA_CAC_AC_A___C_AC__GTA_CAC_AC_G_TA_C__A___C_AC__GTA___C_AC_A___C_____GTA___C_AC___G_T_GTGT__A_C_G_T_GTGT__A__C_GTGT_GTAC_____GT_GT_______GT_______GTA___C_AC_G_T_GTGTA___C_G__TGT_GTAC_____GT_______GT_GTAC______G_T_GTGT__A____________C_AC__GTA___C_A__A___C_AC__GTA_CAC_AC_G_TA_C__A___C_AC__GTA___C_AC_A___C_AC____A___C_AC___G_TA_C____A_________________________________________________________C_AC__GTA_CAC_AC__GTAC_AC____A_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC__GTAC_AC____A___C______G_TA_C____A____________C_AC__GTA_CAC_AC_A___C_AC__GTA_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC__GTAC_AC__GT_GT________G_TA_CGTGT_GTA__C_GTGTGTACG_T_GTGT_GTAC_AC__GT_GT_______GTAC_G__TGT_GTAC____G_T_GTGTA___C_G__TGT_GTAC_AC__GTACACAC__GTA___C_AC___G_T_GTGT__A__C_GTGT_GTAC_____GT_GTAC_AC__GTAC_AC____A___C____G_TA_C__A___C_AC__GTA___C_AC_A___C_AC____A___C_AC_G_TA__CA_________________________________C_AC__GTA_CAC_AC__GTAC_AC____A_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC__GTAC_AC____A___C______G_TA_C____A____________C_AC__GTA_CAC_AC_A___C_AC__GTA_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC__GTAC_AC__GT_GT________G_TA_CGTGT_GTA__C_GTGTGTACG_T_GTGT_GTAC_AC__GT_GT_______GTAC_G__TGT_GTAC____G_T_GTGTA___C_G__TGT_GTAC_AC__GTACACAC__GTA___C_AC___G_T_GTGT__A__C_GTGT_GTAC_____GT_GT_______GTAC_____GT_GT______G_T_GT__A___C_AC__GT_GT_______GTAC_G__TGT_GTAC______G__T_G_T_GT____A__C_G_T_GTGT__A_C_G_TA_C____A____________C_AC__GTA_CAC_AC__GTAC_AC____A___C____G_TA_C__A___C_AC__GTA_CAC_AC_A___C_AC__GTA_CAC_AC___G_TA_C____A____________C_AC__GTA_CAC_AC__GTAC_ACG_TGT_GTAC____G_T_GTGTA___C_G__TGT_GTAC_____GTG_____TGT_GTAC_AC___G_T_GTGT__A_C_G_T_GTGT__A__C_GTGT_GTAC_G__TGT_GTAC_AC__GTACACAC__GTA___C_AC_G_T_GTGTA___C_G__TGT_GTAC_____GT_______GT_GTAC______G_T_GTGTGTA__CACGTGT_GTAC_G__TGT_GTAC_____GT_______GT_GTAC____G_T_GTGT_GTAC_G__TGT_GT_______GTAC_AC__GT_GT______G_TA__C_GTGTGTA_C_G_T_GTGT__A__C_GTGT_GTAC_____GTA_CAC_AC__GTACACAC__GTA_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC_A___C_AC__GTA_CAC_AC___G_TA_C____A____________C_AC__GTA_CAC_AC__GTAC_ACG_TGT_GTAC____G_T_GTGTA___C_G__TGT_GTAC_____GTG_____TGT_GTAC_AC___G_T_GTGT__A_C_G_T_GTGT__A__C_GTGT_GTAC_G__TGT_GTAC_AC__GTACACAC__GTA___C_AC_G_T_GTGTA___C_G__TGT_GTAC_____GT_______GT_GTAC______G_T_GTGTGTA____________C_AC__GT_GT_______GTAC_G__TGT_GTAC____G_T_GTGTA___C_____GT_GT_______GT_C_AC__GTA___C_AC___G_T_GTGT__A___C_G_T_GTGT__A__C_G_T_GTGT__A_C_G_T_GTGTGTA__CACGTGT_GTAC_G__TGT_GTAC_____GT_______GT_GTAC____G_T_GTGTA___C_____GTA_CAC_AC__GTACACAC__GTA_CAC_AC___G_TA_C____A____________C_AC__GTA_CAC_AC_A___C_AC__GTA_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC__GTAC_AC__GT_GT________G_TA_CGTGT_GTA__C_GTGTGTACG_T_GTGT_GTAC_AC__GT_GT_______GTAC_G__TGT_GTAC____G_T_GTGTA___C_G__TGT_GTAC_AC__GTACACAC__GTA___C_AC___G_T_GTGT__A__C_GTGT_GTAC_G__TGT_GTAC_____GTG_____TGT_GTAC_AC_G_T_GTGTA___C_G__TGT_GTAC_____GT_______GT_GTAC____G_T_G_T_GTGT__A_C_G_T_GTGTGTA__CACGTGT_GTAC_G__TGT_GTAC_____GT_______GT_GTAC____G_T_GTGTA___C_____GTA_CAC_AC__GTACACAC__GTA_CAC_AC___G_TA_C____A____________C_AC__GTA_CAC_AC_A___C_AC__GTA_CAC_AC_G_TA_C__A___C_AC__GTA_CAC_AC__GTAC_AC__GT_GT________G_TA_CGTGT_GTA__C_GTGTGTACG_T_GTGT_GTAC_AC__GT_GT_______GTAC_G__TGT_GTAC____G_T_GTGTA___C_G__TGT_GTAC_AC__GTACACAC__GTA___C_ACG_T_GTGTACGTGTGTA__C_GTGT_GTAC_G__TGT_GT_______GTAC_ACG_TGT_GTAC____G_T_GTGTA___C_G__TGT_GTAC_____GT_______GT_GT______";
		String eff2_2_grader = "GTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGTAGGTAGTGTGGTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCTAGGTAGTGT__GTAGTAGGTA_GTGTGTA_GGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTA_GGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTA_GGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCAC_CTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTA_GTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCAC_CTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTA_GTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTA_GGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTA_GTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTA_GGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTAC_CACCTGTAGTACCAC_CTAG_GTA_GTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCAC_CTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACC";

		String eff2_1_group = "____________________________________________________________________________________________________________________________________________________________________A____________CA_C__G__TAC___A__C_ACGTAC__ACAC_G_TAC__ACA_CA_CAC__A_CG___TAC__A_C_A__CGTA_CA_CAC_____GT_ACAC__ACA_CA__CGT_ACA_CA____CGT_A______CACAC_GT_ACAC__A_CGT_ACAC__A_CGT_ACAC__A______CAC_A___C_GT_ACA_CA__CGT_ACA_CA__CGT_ACA__C_A_CGT_ACA__C_____GTGTGTACG_TGTGTACGTGTGT_ACGTG_TG_TGT_ACAC_G__TGTG_______TAC_G__TGTG____T_A_CG___TG_TGT_A__CGTG_TGT_ACAC_G_TA_CA____CACGTA_CA____CG___TGTG__TA_CGTGTG____T_A_CGTG_TAC__A_C__GTA_C__A______CAC_____GT___ACA_CA____CG_TA_CA____C_ACA______C__ACA__C_________________________________G_TA_CA_CAC_G_TA_CA_CAC_G_TA_CA_C______A_CA____C_ACGTAC__ACA__C_GT__A_____C_A_C__A_CG___TAC__A_C________A_______C_GT_ACA_CA____CG_TA_CA_CAC__ACA__C_GT___ACA__C_A_C_GT_ACAC__A_C___GT____A_C_A__CAC_____GT_ACAC_________________________G_______TG_T__GTA_C__GT_______GTG_TA_CG_T_GT_GT__A___CGTG_TG_TGT_ACAC_G__TGT____G___TAC_G__TGTG____T_A_C____G_TGTGTA_C__GTGTG_TA_CA____C_GT__A____CA_ACA__C_GT___ACA__C_A_C_GT_ACAC__A_CG___TAC__A_C_A__CAC______A__CAC_________________________________________________________________GT_ACAC__A_CGT_ACAC__A_CGT_ACAC__A______CAC_A___C_GT_ACA_CA____C_GT__A_____C_ACA__C_GT___ACA__C__________A______CGTA_CA_CAC_____GT_ACAC__ACA_CA____CG_TA_CA____C_ACGTAC__ACAC_G_TAC__ACAC_G_TAC__A_CGTG_T_______GT___ACGTG_TGT_AC_G_TGTGTACG__TGTGTG_TAC__A_CGTG________TGT_A__CGTG_T__GT____A_C_GTGTG_TA_CG_T_GTG_TA_CA__CGT_ACA__C_A_CGT_ACA__C_____GTGTGT_AC_G_TG_T__GTA_C__GT_GT_ACAC__GT__A__C______A_CA____CG___TAC__ACA__C_GT___ACA__C_A_C______A_CA_C__A_C________________________________GT___ACA_CA__CGT_ACA_CA__CGT_ACA______C__ACA__C_A_C_GT_ACAC__A_C___GT____A_C_A__CAC_____GT_ACAC__________________ACGTAC__ACA__C_GT___ACA_CA_CAC__A_CG___TAC__A_C_A__CGTA_CA_CAC___GT____A_C_A____CA____CG_TA_CA________C________________________GTGT_GT__A___CGT_____GT_GT___ACGTG___TGTA___C_G__TGTGTG_TAC__A_CGTG____T____GT_A__CGTG_T__GTA_C_GT______GTGTA__CG_TG_TGT_ACAC_G_TAC__ACAC_G_TAC__A_CGTG________TGTACGTG_TGT_A__CGTG_T__GTA_C__GT__G__T_GTG_TA_CA________C__________GT__GTGT_ACGTG_TGTA__CG_TGTGTA_C__GTGT_GT__A___CGT_ACA_CA__CGT_ACA__C_A_CGT_ACA__C_A_C_GT_ACAC__A_CG___TAC__ACA_CA_CAC_____GT_ACAC__________________ACGTAC__ACAC_G_TAC__ACAC_G_TAC__A_CGTG____T____GTACGTG_TGT_A__CGTG_T__GTA_C__GT__G__T_GTG_TA_CA____C____G_TG_TGTA__CG_TGTGTA_C__GTGTG_TA_CG_T_GTG_TA_CA__CGT_ACA__C_A_CGT_ACA__C_GT__GTG____T_A_CGTG________TGT_A__CGTG_T__GTA_C_G____TGTGTGTA__CACGTG_TGTA___C_G__TGTG_______TAC_G__TGTG____T_A_CGTG_TG_TGT_A__CGTG_T______GTG_TA_CA____C_GT_GT______GT___ACGTG_TGT_AC_G_TGTG__TA_CGTGTG____T_A_CGT_ACAC__A_CGT_ACAC_A___CGT_ACAC_A___C_GT_ACA_CA____CG_TA_CA_CAC__ACA__C_GT___ACA__C__A______________CGTA_CA_CAC_G_TA_CA_CAC_G_TA_CA__CGT_GT_GT______ACGTG_TGT_ACGTG___TGTA___C_G____TG__TGTG_TAC__A_CG_______TG_TGT_AC_G_TGTG__TA_CGTGTG____T_A_CGTG________TGT_ACAC_____GT_ACAC_A___C___G_TA_CA__CGT_____GT_GT___ACGTG___TGT__A_C_______GTGTGT_ACGTG_TG_TGT_ACAC__GT_______GTG_TA_CG_T_GT_GT____A_C__G_TG_TGTA___C_G__TGT____G___T__C_A_CG___TAC__A_C_________GT_GT__GT___ACGTG_TG_TA_C__GTGTGT_AC__G_TGTGTGTA__CACGTG_TGTA___C_G__TGTG_______TAC_G__TGTG____T_A_CG___TG_T__GTA_C_G_TA_CA_CAC_G_TA_CA____CACGTA_CA____CA_C_____________GT_ACAC__A_CG___TAC__ACA_CA_CAC_____GT_ACAC_A___C_GT_ACA_CA__CGT_ACA_CA__CGT_ACAC_G__T_G_T______G_TAC_GTGTG___TA_CGTGTGT_ACGTG_TG_TGT_ACAC_G__TGTG_______TAC_G__TGTG____T_A_CG___TG_TGT_A__CGTG_TGT_ACAC_G_TA_CA____CACGTA_CA____CGT______________GTG____T_A_CGTG________TGT_A__CGTG_T__GTA_C__GT_GTGTG_TA_CA__CGT_____GT_GT__A___C_G__TGTG_________TA_CGTGTGT_A_C_GT_GTGTGT_ACGTG_TG_TGT_ACAC__GT_______GTG_TA_CG_T_GT_GT____A_C__G_TG_TGT_ACGTG___TGTA___C_G_TAC__A_C__ACGTAC__A_CA_______________C_GT_ACA_CA__CGT_ACA_CA__CGT_ACA______C__ACA__C_A_C_GT_ACAC__A_CGT_ACAC__A_CGT_ACAC_A___CGT_ACAC_GT______GTGTACG_TGTGTACGTGTGT_ACGTG_TG_TGT_ACAC__GT_______GTG_TA_CG_T_GT_GT____A_C__G_TG_TGT_ACGTG___TGT_ACAC_G_TAC__A_C__ACGTAC__ACGTG_TGT_ACGTG_TG_TACGTGTG_TA_CG_T_GT_____GT_GT___ACAC_G__TGTG_______TACGTGTG____T_A_CGTG____T____GT_A__CGTG_T______GT";
		String eff2_2_group = "GTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGTAGGTAGTGTGGTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGT_ACCACCTAGGTAGTGTGTA_GTAG_GTAGT_GTGTAGGT_AGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTA_GTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTAG_GTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGT_ACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTA_GTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGT_ACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTA_GTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGT_ACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTA_GTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGT_ACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTA_GTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGT_AGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGGGTAGGTAGTGTGTAGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGTA_GTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTA_GTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCTAGGTAGTGTGTAGTAGGTAGTGTGTAGGT_AGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTA_GTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGGTAGTGTGTAGTAGGTAGTGTGTAGGT_AGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTA_GTACCACCTAGGTAGTGTGTAGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGT_ACCACCTAGGTAGTGTGTA_GTAG_GTAGT_GTGTAGGT_AGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGTGTAGTACCACCTGTAGTACCACCAGTACCACCTGTA_GTACCACC_TAGGT_AGTGTGTAGGTAGT_GTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACCGGTAGT_GTAGTACCACCTGTAGTACCACCAGTACCACCTGTAGTACCACC";

		System.out.printf("[Gap Count] - eff1_1_grader : %d\r\n",gapCounters(eff1_1_grader));
		System.out.printf("[Str Count] - eff1_1_grader : %d\r\n",eff1_1_grader.length());

		System.out.printf("[Gap Count] - eff1_1_group : %d\r\n",gapCounters(eff1_1_group));
		System.out.printf("[Str Count] - eff1_1_group : %d\r\n",eff1_1_group.length());
		System.out.println("==================================");
		System.out.printf("[Gap Count] - eff1_2_grader : %d\r\n",gapCounters(eff1_2_grader));
		System.out.printf("[Str Count] - eff1_2_grader : %d\r\n",eff1_2_grader.length());

		System.out.printf("[Gap Count] - eff1_2_group : %d\r\n",gapCounters(eff1_2_group));
		System.out.printf("[Str Count] - eff1_2_group : %d\r\n",eff1_2_group.length());
		System.out.println("==================================");
		System.out.printf("[Gap Count] - eff2_1_grader : %d\r\n",gapCounters(eff2_1_grader));
		System.out.printf("[Str Count] - eff2_1_grader : %d\r\n",eff2_1_grader.length());

		System.out.printf("[Gap Count] - eff2_1_group : %d\r\n",gapCounters(eff2_1_group));
		System.out.printf("[Str Count] - eff2_1_group : %d\r\n",eff2_1_group.length());
		System.out.println("==================================");
		System.out.printf("[Gap Count] - eff2_2_grader : %d\r\n",gapCounters(eff2_2_grader));
		System.out.printf("[Str Count] - eff2_2_grader : %d\r\n",eff2_2_grader.length());

		System.out.printf("[Gap Count] - eff1_2_group : %d\r\n",gapCounters(eff2_2_group));
		System.out.printf("[Str Count] - eff1_2_group : %d\r\n",eff2_2_group.length());


	}

}

